apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordcount-api
  labels:
    app: wordcount-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordcount-api
  template:
    metadata:
      labels:
        app: wordcount-api
    spec:
      containers:
      - name: api
        image: <seu-registry>/wordcount-api:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
